### ISSUE TITLE
[SVE] Test_TC_CADMIN_1_16.yaml makes assumptions not supported by the spec

### ISSUE THREAD

**Issue by raju-apple** [project-chip/matter-test-scripts#11]
From chip-test-scripts created by [bzbarsky-apple](https://github.com/bzbarsky-apple): CHIP-Specifications/chip-test-scripts#666  

## Description:
See https://github.com/project-chip/connectedhomeip/issues/29375

The test expects fabric info entries to come in a particular order, but the spec does not require that.

**Comment by raju-apple** [comment]
I understand the specification doesn't mandate the order or fabric list. But the YAML has no support for verifying list values regardless of order, I have already raised an SDK issue seeking the support for the same [24149](https://github.com/project-chip/connectedhomeip/issues/24149).

Until we wait for the SDK team to come back, Only option for YAML script i can think of is, we may read the Fabrics attribute without response check and with a prompt we could ask the user to check whether the values of the Fabric list CONTAINS only Fabric-index values 1, 3, 4.
@bzbarsky-apple What is your thoughts on this?

**Comment by raju-apple** [comment]
@manjunath-grl https://github.com/project-chip/connectedhomeip/pull/29643 should make it so you can use `contains` and `excludes` on lists of structs. Note that https://github.com/project-chip/connectedhomeip/issues/24149 is about a completely different situation that has nothing to do with this one...

With the PR above, I guess you can have something like:
```
    contains: [ entries here]
    maxLength: length-of-entries # To make sure there's nothing extra in the list
``` 
or so.

**Comment by manjunath-grl** [comment]
@raju-apple Fixed in PR [29883](https://github.com/project-chip/connectedhomeip/pull/29883) please verify it and close the ticket.

**Comment by Apollon77** [comment]
@manjunath-grl @raju-apple SOrry to bring it up but for me with a current "master" of tests and yaml I still get the same eror on CADMIN_1_16:

Matter.js log:
```
2024-01-20 21:25:29.793 DEBUG   2024-01-20 21:25:29.793 DEBUG InteractionServer Read attribute from udp://fe80::cd2:de55:1cee:150d%en7:53008 on session secure/62193: MA-rootdevice(0x0)/OperationalCredentials(0x3e)/fabrics(0x1)=[{"fabricId":"1","label":"","nodeId":"305414945","rootPublicKey":"04e88fefeb51fc718f9ec623811c41a134ca88fc1ff5ee8c72356e2bf04358462bf933a8edc6b064dce8528ee99b0aa090b8417b52b2cb5dedbd083fa2e821b975","vendorId":65521,"fabricIndex":1},{"fabricId":"3","label":"","nodeId":"12586990","rootPublicKey":"049543899360cc70d905e95c93795f2ee6c696ea9aefdb488fb611a0d9c640c9f733963956117647e091b1dd01857f2d827e369c2263a5093ef00837670c6c7cab","vendorId":65521,"fabricIndex":3},{"fabricId":"2","label":"","nodeId":"51966","rootPublicKey":"049543899360cc70d905e95c93795f2ee6c696ea9aefdb488fb611a0d9c640c9f733963956117647e091b1dd01857f2d827e369c2263a5093ef00837670c6c7cab","vendorId":65521,"fabricIndex":4}] (version=1335894875)
```

test log:

```
2024-01-20 21:25:30.050 ERROR   21:25:29.813 - TEST OUT  : 		    Expected: [
2024-01-20 21:25:30.050 ERROR   21:25:29.813 - TEST OUT  : 		                {
2024-01-20 21:25:30.050 ERROR   21:25:29.813 - TEST OUT  : 		                  "values": [
2024-01-20 21:25:30.050 ERROR   21:25:29.813 - TEST OUT  : 		                    {
2024-01-20 21:25:30.050 ERROR   21:25:29.813 - TEST OUT  : 		                      "constraints": {
2024-01-20 21:25:30.050 ERROR   21:25:29.813 - TEST OUT  : 		                        "type": "list"
2024-01-20 21:25:30.050 ERROR   21:25:29.813 - TEST OUT  : 		                      },
2024-01-20 21:25:30.050 ERROR   21:25:29.814 - TEST OUT  : 		                      "value": [
2024-01-20 21:25:30.050 ERROR   21:25:29.814 - TEST OUT  : 		                        {
2024-01-20 21:25:30.050 ERROR   21:25:29.814 - TEST OUT  : 		                          "FabricIndex": 1,
2024-01-20 21:25:30.050 ERROR   21:25:29.814 - TEST OUT  : 		                          "Label": "",
2024-01-20 21:25:30.050 ERROR   21:25:29.814 - TEST OUT  : 		                          "NodeID": 305414945
2024-01-20 21:25:30.050 ERROR   21:25:29.814 - TEST OUT  : 		                        },
2024-01-20 21:25:30.050 ERROR   21:25:29.814 - TEST OUT  : 		                        {
2024-01-20 21:25:30.050 ERROR   21:25:29.814 - TEST OUT  : 		                          "FabricIndex": 4,
2024-01-20 21:25:30.050 ERROR   21:25:29.814 - TEST OUT  : 		                          "Label": "",
2024-01-20 21:25:30.050 ERROR   21:25:29.814 - TEST OUT  : 		                          "NodeID": 51966
2024-01-20 21:25:30.051 ERROR   21:25:29.814 - TEST OUT  : 		                        },
2024-01-20 21:25:30.051 ERROR   21:25:29.814 - TEST OUT  : 		                        {
2024-01-20 21:25:30.051 ERROR   21:25:29.814 - TEST OUT  : 		                          "FabricIndex": 3,
2024-01-20 21:25:30.051 ERROR   21:25:29.814 - TEST OUT  : 		                          "Label": "",
2024-01-20 21:25:30.051 ERROR   21:25:29.814 - TEST OUT  : 		                          "NodeID": 12586990
2024-01-20 21:25:30.051 ERROR   21:25:29.814 - TEST OUT  : 		                        }
2024-01-20 21:25:30.051 ERROR   21:25:29.814 - TEST OUT  : 		                      ]
2024-01-20 21:25:30.051 ERROR   21:25:29.814 - TEST OUT  : 		                    }
2024-01-20 21:25:30.051 ERROR   21:25:29.815 - TEST OUT  : 		                  ]
2024-01-20 21:25:30.051 ERROR   21:25:29.815 - TEST OUT  : 		                }
2024-01-20 21:25:30.051 ERROR   21:25:29.815 - TEST OUT  : 		              ]
2024-01-20 21:25:30.051 ERROR   21:25:29.815 - TEST OUT  : 		    Received: [
2024-01-20 21:25:30.051 ERROR   21:25:29.815 - TEST OUT  : 		                 {
2024-01-20 21:25:30.051 ERROR   21:25:29.815 - TEST OUT  : 		                   "attribute": "Fabrics",
2024-01-20 21:25:30.051 ERROR   21:25:29.815 - TEST OUT  : 		                   "cluster": "OperationalCredentials",
2024-01-20 21:25:30.051 ERROR   21:25:29.815 - TEST OUT  : 		                   "dataVersion": 1335894875,
2024-01-20 21:25:30.051 ERROR   21:25:29.815 - TEST OUT  : 		                   "endpoint": 0,
2024-01-20 21:25:30.051 ERROR   21:25:29.815 - TEST OUT  : 		                   "value": [
2024-01-20 21:25:30.051 ERROR   21:25:29.815 - TEST OUT  : 		                     {
2024-01-20 21:25:30.051 ERROR   21:25:29.815 - TEST OUT  : 		                       "FabricID": 1,
2024-01-20 21:25:30.051 ERROR   21:25:29.815 - TEST OUT  : 		                       "FabricIndex": 1,
2024-01-20 21:25:30.051 ERROR   21:25:29.815 - TEST OUT  : 		                       "Label": "",
2024-01-20 21:25:30.052 ERROR   21:25:29.815 - TEST OUT  : 		                       "NodeID": 305414945,
2024-01-20 21:25:30.052 ERROR   21:25:29.815 - TEST OUT  : 		                       "RootPublicKey": "\u0004\u00e8\u008f\u00ef\u00ebQ\u00fcq\u008f\u009e\u00c6#\u0081\u001cA\u00a14\u00ca\u0088\u00fc\u001f\u00f5\u00ee\u008cr5n+\u00f0CXF+\u00f93\u00a8\u00ed\u00c6\u00b0d\u00dc\u00e8R\u008e\u00e9\u009b\n\u00a0\u0090\u00b8A{R\u00b2\u00cb]\u00ed\u00bd\b?\u00a2\u00e8!\u00b9u",
2024-01-20 21:25:30.052 ERROR   21:25:29.815 - TEST OUT  : 		                       "VendorID": 65521
2024-01-20 21:25:30.052 ERROR   21:25:29.815 - TEST OUT  : 		                     },
2024-01-20 21:25:30.052 ERROR   21:25:29.816 - TEST OUT  : 		                     {
2024-01-20 21:25:30.052 ERROR   21:25:29.816 - TEST OUT  : 		                       "FabricID": 3,
2024-01-20 21:25:30.052 ERROR   21:25:29.816 - TEST OUT  : 		                       "FabricIndex": 3,
2024-01-20 21:25:30.052 ERROR   21:25:29.816 - TEST OUT  : 		                       "Label": "",
2024-01-20 21:25:30.052 ERROR   21:25:29.816 - TEST OUT  : 		                       "NodeID": 12586990,
2024-01-20 21:25:30.052 ERROR   21:25:29.816 - TEST OUT  : 		                       "RootPublicKey": "\u0004\u0095C\u0089\u0093`\u00ccp\u00d9\u0005\u00e9\\\u0093y_.\u00e6\u00c6\u0096\u00ea\u009a\u00ef\u00dbH\u008f\u00b6\u0011\u00a0\u00d9\u00c6@\u00c9\u00f73\u00969V\u0011vG\u00e0\u0091\u00b1\u00dd\u0001\u0085\u007f-\u0082~6\u009c\"c\u00a5\t>\u00f0\b7g\fl|\u00ab",
2024-01-20 21:25:30.052 ERROR   21:25:29.816 - TEST OUT  : 		                       "VendorID": 65521
2024-01-20 21:25:30.052 ERROR   21:25:29.816 - TEST OUT  : 		                     },
2024-01-20 21:25:30.052 ERROR   21:25:29.816 - TEST OUT  : 		                     {
2024-01-20 21:25:30.052 ERROR   21:25:29.816 - TEST OUT  : 		                       "FabricID": 2,
2024-01-20 21:25:30.052 ERROR   21:25:29.816 - TEST OUT  : 		                       "FabricIndex": 4,
2024-01-20 21:25:30.052 ERROR   21:25:29.816 - TEST OUT  : 		                       "Label": "",
2024-01-20 21:25:30.052 ERROR   21:25:29.816 - TEST OUT  : 		                       "NodeID": 51966,
2024-01-20 21:25:30.052 ERROR   21:25:29.816 - TEST OUT  : 		                       "RootPublicKey": "\u0004\u0095C\u0089\u0093`\u00ccp\u00d9\u0005\u00e9\\\u0093y_.\u00e6\u00c6\u0096\u00ea\u009a\u00ef\u00dbH\u008f\u00b6\u0011\u00a0\u00d9\u00c6@\u00c9\u00f73\u00969V\u0011vG\u00e0\u0091\u00b1\u00dd\u0001\u0085\u007f-\u0082~6\u009c\"c\u00a5\t>\u00f0\b7g\fl|\u00ab",
2024-01-20 21:25:30.052 ERROR   21:25:29.816 - TEST OUT  : 		                       "VendorID": 65521
2024-01-20 21:25:30.052 ERROR   21:25:29.816 - TEST OUT  : 		                     }
2024-01-20 21:25:30.052 ERROR   21:25:29.816 - TEST OUT  : 		                   ]
2024-01-20 21:25:30.052 ERROR   21:25:29.816 - TEST OUT  : 		                 }
2024-01-20 21:25:30.052 ERROR   21:25:29.817 - TEST OUT  : 		               ]
2024-01-20 21:25:30.053 ERROR   21:25:29.817 - TEST OUT  : 		***** Test Failure : The test expectation "value == [{'Label': '', 'FabricIndex': 1, 'NodeID': 305414945}, {'Label': '', 'FabricIndex': 4, 'NodeID': 51966}, {'Label': '', 'FabricIndex': 3, 'NodeID': 12586990}]" is false

```

It seems that he "contains is not enough ... sorry

**Comment by Apollon77** [comment]
Also verified. Works
